version: "3.8"

services:
  sockrustet:
    image: garneck/sockrustet:latest
    container_name: sockrustet
    restart: always
    environment:
      - RUST_LOG=info
      - EMIT_API_KEYS=your_emit_key_here
      - SUBSCRIBE_API_KEYS=your_subscribe_key_here
      - PRODUCTION=true
    ports:
      - "3030:3030"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
