name: Publish Scratch Docker image (ARM64 Only)

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]

env:
  REGISTRY: docker.io
  IMAGE_NAME: garneck/sockrustet
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup for ARM64 build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          # Create a builder that persists cache between runs
          driver-opts: |
            network=host
            image=moby/buildkit:buildx-stable-1
          buildkitd-flags: --debug

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=arm64,enable={{is_default_branch}}

      # Build and push using scratch-optimized settings (ARM64 only)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          # Improved cache configuration - use a registry cache
          cache-from: |
            type=gha,scope=docker-build-arm64-${{ github.ref_name }}
            type=gha,scope=docker-build-arm64-main
          cache-to: type=gha,mode=max,scope=docker-build-arm64-${{ github.ref_name }}
          # Optimizations for scratch image
          provenance: false
          sbom: false
          # Show build progress and add timeouts
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            DOCKER_TIMEOUT=30m
          # Add fail-fast and resource constraints
          builder-to-load-args: |
            --progress=plain
          # Allow more time for ARM64 builds
          timeout-minutes: 60
